spring:
  application:
    name: infuq-export-provider
  redis:
    host: 192.168.10.21
    port: 6379
    database: 2
    password: baidon@2021
  datasource:
    url: jdbc:mysql://rm-bp1349lz8ic76gru5.mysql.rds.aliyuncs.com:3306/wisp_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: bd_test_user
    password: nhpG4N5VA3Sz
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maxPoolSize: 10
      minIdle: 5

server:
  port: 58081
  tomcat:
    basedir: /Users/infuq/logs/tmp
    max-threads: 100
    min-spare-threads: 20
    accept-count: 100

