spring:
  application:
    name: infuq-export
  redis:
    host: 172.31.3.199
    port: 6379
    database: 2
    password: 9527
  datasource:
    dynamic:
      primary: master
      p6spy: true
      datasource:
        master:
          url: jdbc:mysql://172.31.3.199:3306/db0
          username: root
          password: 9527
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
          druid:
            initial-size: 5
            min-idle: 5
            maxActive: 50
            maxWait: 60000
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
        slave:
          url: jdbc:mysql://172.31.3.199:3306/db0
          username: root
          password: 9527
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
          druid:
            initial-size: 3
            min-idle: 3
            maxActive: 50
            maxWait: 60000
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000


  cloud:
    sentinel:
      transport:
        dashboard: http://172.31.3.199:8858


management:
  endpoint:
      health:
        show-details: always


server:
  port: 58082
  tomcat:
    basedir: /home/v-infuq/logs/tmp

