spring:
  application:
    name: infuq-export-consumer
  redis:
    host: 192.168.31.131
    port: 6379
    database: 1
  datasource:
    url: jdbc:mysql://192.168.31.131:3306/db0?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 9527
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maxPoolSize: 10
      minIdle: 5